# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Website for CodeCademy Course
email: leondrisalas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's just a test Website for the Codecademy course about Deploy a Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leondrisalas.github.io/" # the base hostname & protocol for your site
twitter_username: leondrisalas
github_username:  leondrisalas

# Build settings
markdown: kramdown
